[out:json][timeout:180];
(
  way["waterway"]["name"~"Paraopeba|São Francisco|Sao Francisco|Velhas|Cristalino|Água Preta|Agua Preta|Sumidouro|Sacré|Sacre|Paraim|Maranhão|Maranhao|Almas|Verde Grande|Rio Claro",i](-21,-62,-11,-43);
  relation["waterway"]["name"~"Paraopeba|São Francisco|Sao Francisco|Velhas|Cristalino|Água Preta|Agua Preta|Sumidouro|Sacré|Sacre|Paraim|Maranhão|Maranhao|Almas|Verde Grande|Rio Claro",i](-21,-62,-11,-43);
);
out geom;
